### PR TITLE
F/choose method for extracting external ip

### PR DESCRIPTION
**Pull request by Blackstareye**
Adds the ability to choose how the external server ip should be extracted.

There are 3 methods implemented right now:

1) **who-am-i**, via dig request to who-am-i, the external ip will be determined (FarrowStrange's Approach)
2) **server**, use your own server to determine the external ip. I added a simple php script to the repo for the backend; it is also possible to protect the backend via .htaccess and using credentials (basic auth).
3)  **fritzbox**, use fritzbox's  functionality to determine the current external ip using 
     [this script from ubuntuusers](https://wiki.ubuntuusers.de/FritzBox/Skripte/)
     I added a script called 'localservice.sh" for that purpose.

### CODE REVIEW

**Comment by FarrowStrange** [comment]
Hey @Blackstareye 

Thank you for your contribution.

Unfortunately I didn't have much time for this repository in the last months. I will review all open pull requests soon.

**Comment by FarrowStrange** [comment]
After this project has the goal to work out of the box and there is already another PR open with a very good implementation of the hetzen lookup service, i have to close this PR unfortunately. 

Thanks a lot for your efforts.

**Comment by Blackstareye** [comment]
Does this approach includes alternate methods for public ip extraction ?
I don't wanna use cloudflare for that.

So selfhosted solutions have also there purpose :) 

If the "very good implementation" has this, i am happy with that.
Otherwise, I just use my own fork :)

**Comment by FarrowStrange** [comment]
Hey @Blackstareye,

the new method implemented in #35 uses Hetzer's own service `ip.hetzner.com` to determine the public ip.
Maybe this is an alternative for you.

**Comment by Blackstareye** [comment]
It's a good strategy if you have your server on hetzner and also your dns entry.
If you don't have this, you have the same problem.

So yeah it's a nice solution but it doesn't solve the issue on a selfhosted perspective

**Comment by FarrowStrange** [comment]
You do not need a server at Hetzner for this.

When you call the script from your home network, the DNS record is set to the public IP of your router. This project is about the implementation of dynamic DNS records via the Hetzner API.

**Comment by Blackstareye** [comment]
Yes. But there are usecases where I want to controll which external ip resolver I want to use. 
This is not necessary hetzner. 
So yeah for the general purpose this can be done with the new method.
But for me this is not the way I want to do it. I want to control which server resolves my ip.
And so this is the only way I can have fully control over this :)

But still, thank you for reviewing my PR. 
I will use my fork for that case :) 

I can totally understand that this is maybe too specific for the general purpose of your project

**Pull request closed without merging**
